### ISSUE TITLE
CI Failure: No source files were found in the test report payload

### ISSUE THREAD

**Issue by rye** [frc-frecon/frecon#86]
I'm noticing a problem in the CI logs, CodeClimate is throwing an error.

```
Coverage = 100.0%. Code Climate encountered an exception: CodeClimate::TestReporter::InvalidPayload
No source files were found in the test report payload
/home/travis/.rvm/gems/ruby-2.2.3/gems/codeclimate-test-reporter-0.4.8/lib/code_climate/test_reporter/payload_validator.rb:18:in `validate'
/home/travis/.rvm/gems/ruby-2.2.3/gems/codeclimate-test-reporter-0.4.8/lib/code_climate/test_reporter/payload_validator.rb:11:in `validate'
/home/travis/.rvm/gems/ruby-2.2.3/gems/codeclimate-test-reporter-0.4.8/lib/code_climate/test_reporter/formatter.rb:21:in `format'
/home/travis/.rvm/gems/ruby-2.2.3/gems/simplecov-0.11.1/lib/simplecov/result.rb:46:in `format!'
/home/travis/.rvm/gems/ruby-2.2.3/gems/simplecov-0.11.1/lib/simplecov/configuration.rb:168:in `block in at_exit'
/home/travis/.rvm/gems/ruby-2.2.3/gems/simplecov-0.11.1/lib/simplecov/defaults.rb:64:in `call'
/home/travis/.rvm/gems/ruby-2.2.3/gems/simplecov-0.11.1/lib/simplecov/defaults.rb:64:in `block in <top (required)>'
```

I know for a fact that our coverage isn't 100%, and an empty payload could cause this.

**Comment by rye** [comment]
After poking around, removing the `require "frecon"` line from the `spec_helper.rb` file seems to clean this up.  It also helps to ensure that our code is isolated and does not depend on other code being loaded beforehand.

**Comment by rye** [comment]
Fix is on the way.
